name: CI/CD

on: 
  push:
    branches:
      - main

jobs:
  build:
    name: Building image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
        
      - name: DockerHub login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: wolfspelz/jmp1:latest
          
  deploy:
    name: Updating prod environment
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Replacing container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOSTNAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker image pull wolfspelz/jmp1
            docker container stop jmp1-prod
            docker container prune -f
            docker run -d --name jmp1-prod --restart unless-stopped -p 127.0.0.1:5002:80 -it wolfspelz/jmp1
            docker image prune -f
